# Generated by Django 3.2.4 on 2021-06-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
